### ISSUE TITLE
Error: expected string, got number

### ISSUE THREAD

**Issue by medwatt** [nvimtools/hydra.nvim#60]
I am using neovim 10.4 and the latest version of hydra.

This is how I load hydra:

```lua
{
    "nvimtools/hydra.nvim",
    keys = {
        { "<F5>",     mode = "n" },
    },
    config = function() require("plugins.hydra.dap") end,
},
```

This is my hydra config:

```lua
-- imports <<<
local Hydra = require("hydra")
local dap = require("dap")
-- >>>

-- debugging menu <<<
local hint = [[
_s_: start / continue  _i_: step into
_r_: restart           _n_: step over
^^                     _o_: step out
_K_: eval              _c_: to cursor
^ ^
                      _q_: quit debugging
]]
-- >>>

-- func: dap functions <<<
local function StartDap()
    local bufnr = vim.api.nvim_get_current_buf()
    local filetype = vim.api.nvim_buf_get_option(bufnr, 'filetype')
    if filetype == 'lua' then
        require("osv").run_this()
    else
        dap.continue()
    end
end

local function TerminateDap()
    require('dapui').close()
    require('dap').repl.close()
    require('dap').terminate()
end
-- >>>

local dap_hydra = Hydra({
    name = "dap",
    mode = { "n", "x" },
    body = "<F5>",
    hint = hint,
    config = {
        color = "pink",
        invoke_on_body = true,
        hint = {
            show_name = true,
            position = "bottom-right",
            float_opts = {
                border = "single",
            },
        },
    },
    heads = {
        { "n", dap.step_over,                                { silent = true } },
        { "i", dap.step_into,                                { silent = true } },
        { "o", dap.step_out,                                 { silent = true } },
        { "c", dap.run_to_cursor,                            { silent = true } },
        { "r", dap.restart,                                  { silent = true } },
        { "s", StartDap,                                     { silent = true } },
        { "q", TerminateDap,                                 { silent = true, exit=true }},
        { "K", function() require('dap.ui.widgets').hover() end, { silent = true } },
    }
})

dap_hydra:activate()
```

When I activate hydra, I get the following error:

```
Failed to run `config` for hydra.nvim

vim/shared.lua:0: s: expected string, got number

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - vim/shared.lua:0 _in_ **startswith**
  - vim/_init_packages.lua:0 _in_ **__index**
  - vim/shared.lua:0 _in_ **islist**
  - vim/shared.lua:0 _in_ ****
  - vim/shared.lua:0 _in_ **tbl_deep_extend**
  - /hydra.nvim/lua/hydra/layer/init.lua:116 _in_ **initialize**
  - /hydra.nvim/lua/hydra/lib/class.lua:14 _in_ **Layer**
  - /hydra.nvim/lua/hydra/init.lua:440 _in_ **_setup_pink_hydra**
  - /hydra.nvim/lua/hydra/init.lua:282 _in_ **initialize**
  - /hydra.nvim/lua/hydra/lib/class.lua:14 _in_ **Hydra**
  - .config/nvim/lua/plugins/hydra/dap.lua:35
  - .dot/config/nvim/init.lua:150 _in_ **config**
```

If I change the color from pink to red, I got a different error (see video). Pressing F5 once more loads the menu. I can now start using hydra, but it closes after every key press. I have to continuously reopen it with F5.

https://github.com/user-attachments/assets/a31539c1-475b-4531-b21f-c9e8e58b85c6

To be clear, debugging works by executing the commands through which key as you can see in the video:

https://github.com/user-attachments/assets/9cda16cc-d62d-4aed-91bb-9636c66a70b6

**Comment by benlubas** [comment]
Should be fixed now

**Comment by hrqmonteiro** [comment]
Still the same here

<img width="1706" alt="Image" src="https://github.com/user-attachments/assets/8aadad0f-0cbf-4d66-9bd7-ece70d204a9c" />

**Comment by RolandWarburton** [comment]
The issue may have regressed, i am getting the same error on 0.11.3

```none
NVIM v0.11.3
Build type: Release
LuaJIT 2.1.1741730670
Run "nvim -V1 -v" for more info
```

<details>
<code>Error detected while processing /home/roland/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/shared.lua:0: s: expected string, got number
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'startswith'
        vim/_init_packages.lua: in function '__index'
        vim/shared.lua: in function 'islist'
        vim/shared.lua: in function ''
        vim/shared.lua: in function 'tbl_deep_extend'
        ...ocal/share/nvim/lazy/hydra.nvim/lua/hydra/layer/init.lua:116: in function 'initialize'
        ...local/share/nvim/lazy/hydra.nvim/lua/hydra/lib/class.lua:14: in function 'Layer'
        ...and/.local/share/nvim/lazy/hydra.nvim/lua/hydra/init.lua:437: in function '_setup_pink_hydra'
        ...and/.local/share/nvim/lazy/hydra.nvim/lua/hydra/init.lua:281: in function 'initialize'
        ...local/share/nvim/lazy/hydra.nvim/lua/hydra/lib/class.lua:14: in function 'Hydra'
        /home/roland/.config/nvim/lua/extensions/hydra/init.lua:7: in function 'setup'
        /home/roland/.config/nvim/lua/extensions/init.lua:11: in main chunk
        [C]: in function 'require'
        /home/roland/.config/nvim/init.lua:15: in main chunk
</code>
</details>

Here is a picture of the error i am getting
<img width="1273" height="517" alt="Image" src="https://github.com/user-attachments/assets/e6c942fe-8af7-4f8e-a237-b731e8ebede2" />

Below is my config for hydra

<details>
<code>
  local Hydra = require('hydra')


  Hydra({
    name = 'Draw Diagram',
    mode = 'n',
    body = '<leader>d',
    hint = [[
    Arrow^^^^^^   Select region with <C-v>
    ^ ^ _K_ ^ ^   _f_: surround it with box
    _H_ ^ ^ _L_
    ^ ^ _J_ ^ ^                      _<Esc>_
    ]],
    config = {
      exit = false,
      foreign_keys = nil,
      color = "pink",
      buffer = true,
      hint = {
        border = 'rounded'
      },
      invoke_on_body = true,
    },
    heads = {
      { 'H',     '<C-v>h:VBox<CR>' },
      { 'J',     '<C-v>j:VBox<CR>' },
      { 'K',     '<C-v>k:VBox<CR>' },
      { 'L',     '<C-v>l:VBox<CR>' },
      { 'f',     ':VBox<CR>',      { mode = 'v' } },
      { '<Esc>', nil,              { exit = true } },
    }
  })
</code>
</details>

**Comment by hrqmonteiro** [comment]
Same thing here

> The issue may have regressed, i am getting the same error on 0.11.3
> 
> ```
> NVIM v0.11.3
> Build type: Release
> LuaJIT 2.1.1741730670
> Run "nvim -V1 -v" for more info
> ```
> 
> Here is a picture of the error i am getting <img alt="Image" width="1273" height="517" src="https://private-user-images.githubusercontent.com/36120361/483417935-e6c942fe-8af7-4f8e-a237-b731e8ebede2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1Njg3MTQsIm5iZiI6MTc1NjU2ODQxNCwicGF0aCI6Ii8zNjEyMDM2MS80ODM0MTc5MzUtZTZjOTQyZmUtOGFmNy00ZjhlLWEyMzctYjczMWU4ZWJlZGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODMwVDE1NDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZDU5MTRiZTViMjBmMWI4OGRkYjM5MWM5NTg2MmFiNjA3MmViZjY1YjhmYjk5YmJkMjc1OGM1NDEzNzZhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.96n5irK6LX_kXwzT4u0m5eyvl7SLKZSOPZlCwzVTjRk">
> 
> Below is my config for hydra
